# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go - CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: wizhi/setup-buf@v1
      with:
        version: '0.36.0'
    - uses: arduino/setup-protoc@v1
      with:
        version: '3.x'


    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
        
    - name: Installing protoc-gen-go
      run: |
        go install github.com/golang/protobuf/protoc-gen-go@latest
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
        
    - name: Compile proto
      run: |
        cd Gocode/proto
        protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative protobuf.proto
    
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v4
      with:
        working-directory: Gocode
        skip-pkg-cache: true
        skip-build-cache: true
    
    - name: Build
      run: |
        cd Gocode
        go build -v ./...

    - name: Test
      run: |
        cd Gocode
        go test -v ./...
